name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  image-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/v}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v3
        id: docker_build
        with:
          context: .
          file: ./Dockerfile
          build-args: |
            "WHATAP=${{ secrets.WHATAP }}"
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/kitpa-server:latest
            ghcr.io/${{ github.repository_owner }}/kitpa-server:${{ env.RELEASE_VERSION }}